### ISSUE TITLE
Debug each level (in any day) in application

### ISSUE THREAD

**Issue by saeidjoker** [XPRIZE/GLEXP-Team-onebillion#18]
##### Component
Each level in application
##### Description
I'm trying to change some levels, making it suitable for RTL languages, but there is no indication about how to change the text direction in localize.md file.
@pbehghader
By the way nice work
##### Severity
- [ ] Low
- [ ] Medium
- [-] High

**Comment by jo-xprize** [comment]
@XPRIZE/glexp-team-onebillion Would you be able to assist @saeidjoker with this?

**Comment by saeidjoker** [comment]
Hi @jo-xprize 
Not Persian specifically. My main job is to make this suitable for Right-To-Left languages (Persian, Arabic, Hebrew, ...)
I understand that "OpenGL ES" files in source code needs to be rewritten in order to be able to support right to left scripts, but I was hoping to receive a detailed instruction on how OpenGL code was written, because this great repository lacks comments in source code.

**Comment by jo-xprize** [comment]
@saeidjoker Could you please include links to the OpenGL files you are referring to?

**Comment by pbehghader** [comment]
Hi @jo-xprize - This is Pooyan from KCIS. Thanks for looking into this issue.

We're assessing the localizability of Onebillion and Kitkitschool for the right to left languages. We're targetting Persian (Farsi), but the results of our assessments could be applied to any RTL language. We're particularly interested in understanding how many lines of code (LOC) needs to be changed to have a cost/effort estimation.

**Comment by onebillion-admin** [comment]
Hi @saeidjoker. RTL support is a future enhancement. It is not included in the current version.

**Comment by jo-xprize** [comment]
@saeidjoker @pbehghader Note that the `supportsRTL` property has been set to `true` in the `AndroidManifest.xml` file: https://github.com/XPRIZE/GLEXP-Team-onebillion/blob/master/app/src/main/AndroidManifest.xml#L50

Which issues did you face when trying to use Right-to-Left (RTL) text?

**Comment by jo-xprize** [comment]
@saeidjoker @pbehghader For Kitkit, however, work on adapting to Right-to-Left languages has already been done. Check out https://github.com/search?q=org%3Amaqsoftware+urdu&type=Issues
